name: designthinking
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth:
  cloud_firestore:
  firebase_storage:
  image_picker:
  camera:
  path_provider:
  path:
  image_cropper:

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - lib/assets/

  uses-material-design: true